# Generated by Django 4.2.16 on 2024-11-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LESSEE', 'Lessee'), ('LESSOR', 'Lessor')], max_length=10, null=True),
        ),
    ]
