# Generated by Django 4.2.16 on 2024-11-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('lessor_id', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('street_adress', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zip_code', models.SmallIntegerField(blank=True, null=True)),
                ('property_type', models.TextField(blank=True, null=True)),
                ('bedrooms', models.FloatField(blank=True, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('available_since', models.DateField(blank=True, null=True)),
                ('guarantor_required', models.BooleanField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyAmentities',
            fields=[
                ('property_id', models.TextField(primary_key=True, serialize=False)),
                ('air_conditioning', models.BooleanField(blank=True, null=True)),
                ('parking', models.BooleanField(blank=True, null=True)),
                ('dishwasher', models.BooleanField(blank=True, null=True)),
                ('heating', models.BooleanField(blank=True, null=True)),
                ('gym', models.BooleanField(blank=True, null=True)),
                ('refrigerator', models.BooleanField(blank=True, null=True)),
                ('laundry', models.BooleanField(blank=True, null=True)),
                ('swimming_pool', models.BooleanField(blank=True, null=True)),
                ('microwave', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'property_amentities',
                'managed': False,
            },
        ),
    ]
