# Generated by Django 4.2.16 on 2024-12-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Properties",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("lessor_id", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("street_address", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("state", models.TextField(blank=True, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=5, null=True)),
                ("property_type", models.TextField(blank=True, null=True)),
                ("bedrooms", models.FloatField(blank=True, null=True)),
                ("bathrooms", models.FloatField(blank=True, null=True)),
                ("available_since", models.DateField(blank=True, null=True)),
                ("guarantor_required", models.BooleanField(blank=True, null=True)),
                ("description", models.TextField()),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False, null=True)),
                (
                    "rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("status_verification", models.SmallIntegerField(default=0, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyAmenities",
            fields=[
                ("property_id", models.TextField(primary_key=True, serialize=False)),
                ("air_conditioning", models.BooleanField(blank=True, null=True)),
                ("parking", models.BooleanField(blank=True, null=True)),
                ("dishwasher", models.BooleanField(blank=True, null=True)),
                ("heating", models.BooleanField(blank=True, null=True)),
                ("gym", models.BooleanField(blank=True, null=True)),
                ("refrigerator", models.BooleanField(blank=True, null=True)),
                ("laundry", models.BooleanField(blank=True, null=True)),
                ("swimming_pool", models.BooleanField(blank=True, null=True)),
                ("microwave", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "property_amentities",
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("property_id", models.TextField()),
                ("file_name", models.TextField()),
                ("url", models.URLField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "property_images",
            },
        ),
        migrations.CreateModel(
            name="PropertyPois",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("property_id", models.TextField()),
                ("poi_name", models.TextField()),
                (
                    "poi_ratings",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("poi_type", models.TextField()),
                ("distance", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "property_pois",
            },
        ),
        migrations.CreateModel(
            name="PropertyWishlist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lessee_id", models.UUIDField()),
                ("property_id", models.UUIDField()),
                ("is_wishlist", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "property_wishlist",
                "unique_together": {("lessee_id", "property_id")},
            },
        ),
    ]
