# Generated by Django 4.2.16 on 2024-12-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="properties",
            name="lessor_id",
        ),
        migrations.AddField(
            model_name="properties",
            name="lessor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.lessor",
                to_field="user_id",
            ),
        ),
    ]
